[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd server && pnpm install --prod --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "cd server && pnpm build"
]

[start]
cmd = "cd server && pnpm start"
